apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::399752553418:role/eks-node-group-nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::399752553418:role/eks-admin
      username: A15User
      groups:
      - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system